#
FROM python:3.11

#
WORKDIR /backend

#
COPY ./requirements.txt /backend/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

#
COPY . /backend

#
CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
