# Use an appropriate base image for your backend, such as python
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app/backend

# Copy the backend files to the container
COPY requirements*.txt ./

# Install virtualenv
RUN pip install virtualenv

# Create and activate a virtual environment
RUN virtualenv venv
RUN . venv/bin/activate

# Install dependencies using the package manager (e.g., pip)
RUN pip install -r requirements.txt

COPY . .

ENV PORT=3000


# Expose the port on which your backend server listens (if applicable)
EXPOSE 3000

# Define the command to run your backend application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000", "--reload"]
