# Base image
FROM python:3.11

# Set the working directory
WORKDIR /backend

# Copy the requirements file
COPY ./requirements.txt /backend/requirements.txt

# Install development dependencies
RUN pip install --no-cache-dir --upgrade -r /backend/requirements.txt

# Copy the application code
COPY . /backend/app

# Set up the development server
CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
